spring:
  datasource:
    url: jdbc:h2:mem:dio2024 # conex√£o + nome do banco
    username: dio2024
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # Acessar o banco visualmente
      settings:
        trace: false
        web-allow-others: false